/** Bundles drizzle/*.sql into a TS module so the deployed app can apply its own migrations. Run after db:generate. */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
const files = readdirSync('drizzle').filter((f) => f.endsWith('.sql')).sort();
const items = files.map((f) => ({ name: f.replace(/\.sql$/, ''), sql: readFileSync(`drizzle/${f}`, 'utf8') }));
writeFileSync('lib/migrations.generated.ts', `// Generated by scripts/embed-migrations.ts. Do not edit.\nexport const MIGRATIONS: { name: string; sql: string }[] = ${JSON.stringify(items, null, 2)};\n`);
console.log(`Embedded ${items.length} migrations.`);
